"""Camp Planner - a small Flask site for cookbooks and trip planners.

Deliberately does NOT do campsite availability search. That part of campfinder
reads booking systems whose terms restrict automated access and permit only
personal, non-commercial use; running it from a shared host for other people
would breach that and would be blocked within days anyway. Everything here is
the user's own data - their recipes, their menus, their trips - which hosts
cleanly. Availability search stays a local CLI.

The planner itself is generated by plan.py, the same module the CLI uses, so
the site and the command line cannot drift apart.
"""

import datetime as dt
import io
import json
import os
import sqlite3
import sys
import time

from flask import (Flask, abort, flash, g, redirect, render_template, request,
                   send_file, session, url_for)

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import plan  # noqa: E402  - the CLI's generator, reused verbatim

from . import cook, store  # noqa: E402

MAX_UPLOAD = 2 * 1024 * 1024          # 2 MB is a very large cookbook
LOGIN_WINDOW, LOGIN_MAX = 300, 8      # attempts per IP per 5 minutes

app = Flask(__name__)
app.config.update(
    MAX_CONTENT_LENGTH=MAX_UPLOAD,
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SAMESITE="Lax",
    SESSION_COOKIE_SECURE=bool(os.environ.get("FLY_APP_NAME")),
)
# On Fly the secret must be set; locally a generated one is fine (it only
# means sessions reset on restart).
app.secret_key = os.environ.get("SECRET_KEY") or os.urandom(32)

_login_hits = {}


# ------------------------------------------------------------ plumbing --
@app.before_request
def load_user():
    g.user = store.session_user(session.get("t"))
    if request.method == "POST" and g.user:
        sent = request.form.get("csrf", "")
        if not sent or sent != g.user["csrf"]:
            abort(400, "bad csrf token")


@app.after_request
def secure_headers(resp):
    resp.headers.setdefault("X-Content-Type-Options", "nosniff")
    resp.headers.setdefault("X-Frame-Options", "DENY")
    resp.headers.setdefault("Referrer-Policy", "same-origin")
    resp.headers.setdefault(
        "Content-Security-Policy",
        "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:")
    return resp


@app.context_processor
def inject():
    return {"user": g.get("user"), "csrf": (g.get("user") or {}).get("csrf", "")}


def require_login():
    if not g.get("user"):
        return redirect(url_for("login", next=request.path))
    return None


def rate_limited(key):
    now = time.time()
    hits = [t for t in _login_hits.get(key, []) if now - t < LOGIN_WINDOW]
    _login_hits[key] = hits + [now]
    return len(hits) >= LOGIN_MAX


# ------------------------------------------------------------ accounts --
@app.route("/")
def index():
    if g.get("user"):
        return redirect(url_for("trips"))
    return render_template("landing.html")


@app.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        email = (request.form.get("email") or "").strip()
        pw = request.form.get("password") or ""
        name = (request.form.get("name") or "").strip()
        if "@" not in email or len(email) > 200:
            flash("Enter a valid email address.")
        elif len(pw) < 10:
            flash("Use a password of at least 10 characters.")
        else:
            try:
                uid = store.create_user(email, pw, name)
            except sqlite3.IntegrityError:
                flash("That email already has an account.")
            except Exception:
                # Never disguise a real failure as a duplicate-email message -
                # that sent me chasing the wrong bug once already.
                app.logger.exception("signup failed")
                flash("Something went wrong creating the account.")
            else:
                session["t"] = store.start_session(uid)
                return redirect(url_for("cookbook"))
    return render_template("signup.html")


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        if rate_limited(request.remote_addr or "?"):
            flash("Too many attempts. Wait a few minutes and try again.")
            return render_template("login.html"), 429
        user = store.verify_user(request.form.get("email", ""),
                                 request.form.get("password", ""))
        if user:
            session["t"] = store.start_session(user["id"])
            nxt = request.args.get("next", "")
            return redirect(nxt if nxt.startswith("/") else url_for("trips"))
        flash("Email or password is incorrect.")
    return render_template("login.html")


@app.route("/logout", methods=["POST"])
def logout():
    store.end_session(session.pop("t", None))
    return redirect(url_for("index"))


# ------------------------------------------------------------ cookbook --
@app.route("/cookbook")
def cookbook():
    if (r := require_login()):
        return r
    return render_template("cookbook.html",
                           recipes=store.list_recipes(g.user["id"]))


@app.route("/cookbook/import", methods=["POST"])
def cookbook_import():
    if (r := require_login()):
        return r
    text, filename = request.form.get("text", ""), ""
    upload = request.files.get("file")
    if upload and upload.filename:
        filename = upload.filename
        raw = upload.read(MAX_UPLOAD + 1)
        if len(raw) > MAX_UPLOAD:
            flash("That file is larger than 2 MB.")
            return redirect(url_for("cookbook"))
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError:
            flash("Upload a text file — .md, .txt, .json or .csv. "
                  "PDFs and images aren't supported yet.")
            return redirect(url_for("cookbook"))

    parsed = cook.parse(text, filename)
    if not parsed:
        flash("Couldn't find any recipes in that. Each recipe needs a name "
              "line, then its ingredients — one per line.")
    else:
        for name, ings in parsed.items():
            store.save_recipe(g.user["id"], name, ings, filename or "pasted")
        flash(f"Imported {len(parsed)} recipe(s): "
              + ", ".join(list(parsed)[:6])
              + ("…" if len(parsed) > 6 else ""))
    return redirect(url_for("cookbook"))


@app.route("/cookbook/<int:rid>/delete", methods=["POST"])
def recipe_delete(rid):
    if (r := require_login()):
        return r
    store.delete_recipe(g.user["id"], rid)
    return redirect(url_for("cookbook"))


# --------------------------------------------------------------- trips --
def blank_trip(name, start, end):
    return {"trip": {"name": name, "start": start, "end": end},
            "legs": [], "days": [], "menu": [], "extras": [],
            "unplaced": [], "menu_notes": []}


@app.route("/trips", methods=["GET", "POST"])
def trips():
    if (r := require_login()):
        return r
    if request.method == "POST":
        name = (request.form.get("name") or "Untitled trip").strip()
        start = request.form.get("start") or dt.date.today().isoformat()
        end = request.form.get("end") or start
        if end < start:
            flash("The end date is before the start date.")
            return redirect(url_for("trips"))
        tid = store.create_trip(g.user["id"], name,
                                blank_trip(name, start, end))
        return redirect(url_for("trip_edit", tid=tid))
    return render_template("trips.html", trips=store.list_trips(g.user["id"]),
                           today=dt.date.today().isoformat())


@app.route("/trips/<int:tid>", methods=["GET", "POST"])
def trip_edit(tid):
    if (r := require_login()):
        return r
    row = store.get_trip(g.user["id"], tid)
    if not row:
        abort(404)
    data = row["data"]

    if request.method == "POST":
        t = data.setdefault("trip", {})
        t["name"] = (request.form.get("name") or t.get("name", "")).strip()
        t["start"] = request.form.get("start") or t["start"]
        t["end"] = request.form.get("end") or t["end"]
        if t["end"] < t["start"]:
            flash("The end date is before the start date — not saved.")
            return redirect(url_for("trip_edit", tid=tid))

        dogname = (request.form.get("dog") or "").strip()
        data["dog"] = {"name": dogname} if dogname else None
        for flag in ("water", "hiking", "cold"):
            data[flag] = bool(request.form.get(flag))

        days, menu = [], []
        for day in plan.daterange(plan.d(t["start"]), plan.d(t["end"])):
            key = day.isoformat()
            items = [ln.strip() for ln in
                     (request.form.get(f"day_{key}") or "").splitlines()
                     if ln.strip()]
            if items:
                days.append({"date": key, "items": items})
            slots = {s: (request.form.get(f"{s}_{key}") or "").strip()
                     for s in ("breakfast", "lunch", "dinner")}
            if any(slots.values()):
                menu.append({"date": key, **slots})
        data["days"], data["menu"] = days, menu

        data["legs"] = []
        for i in range(int(request.form.get("leg_count") or 0)):
            loc = (request.form.get(f"leg_loc_{i}") or "").strip()
            if not loc:
                continue
            data["legs"].append({
                "name": f"Leg {len(data['legs']) + 1}",
                "start": request.form.get(f"leg_start_{i}") or t["start"],
                "end": request.form.get(f"leg_end_{i}") or t["end"],
                "location": loc,
                "confirmation": (request.form.get(f"leg_conf_{i}") or "").strip()})

        data["extras"] = []
        for line in (request.form.get("extras") or "").splitlines():
            line = line.strip()
            if not line:
                continue
            item, _, why = line.partition("|")
            data["extras"].append({"item": item.strip(), "for": why.strip()})

        data["unplaced"] = [ln.strip() for ln in
                            (request.form.get("unplaced") or "").splitlines()
                            if ln.strip()]
        store.save_trip(g.user["id"], tid, data, t["name"])
        flash("Saved.")
        return redirect(url_for("trip_edit", tid=tid))

    t = data["trip"]
    days = plan.daterange(plan.d(t["start"]), plan.d(t["end"]))
    by_day = {e["date"]: e for e in data.get("days", [])}
    by_menu = {e["date"]: e for e in data.get("menu", [])}
    return render_template(
        "trip.html", trip=row, data=data, days=days, by_day=by_day,
        by_menu=by_menu, label=plan.label,
        recipes=sorted(store.recipe_map(g.user["id"])),
        extras_text="\n".join(
            f"{e['item']} | {e.get('for','')}" if isinstance(e, dict) else str(e)
            for e in data.get("extras", [])))


@app.route("/trips/<int:tid>/delete", methods=["POST"])
def trip_delete(tid):
    if (r := require_login()):
        return r
    store.delete_trip(g.user["id"], tid)
    return redirect(url_for("trips"))


# ------------------------------------------------------------- planner --
def hydrate(user_id, data):
    """Attach only the cookbook recipes this trip's menu actually uses.

    Unreferenced recipes are still shopped for by plan.py (that's how
    "Breakfasts (all days)" works), so handing it the whole cookbook would
    buy groceries for every recipe the user has ever saved.
    """
    book = store.recipe_map(user_id)
    used = set()
    for e in data.get("menu", []):
        for slot in ("breakfast", "lunch", "dinner"):
            meal = (e.get(slot) or "").strip()
            if meal in book:
                used.add(meal)
    for name in data.get("always", []):
        if name in book:
            used.add(name)
    return {**data, "recipes": {n: book[n] for n in sorted(used)}}


@app.route("/trips/<int:tid>/grocery")
def grocery(tid):
    if (r := require_login()):
        return r
    row = store.get_trip(g.user["id"], tid)
    if not row:
        abort(404)
    full = hydrate(g.user["id"], row["data"])
    return render_template("grocery.html", trip=row,
                           aisles=plan.build_shopping(full),
                           recipes=full["recipes"])


@app.route("/trips/<int:tid>/planner.xlsx")
def planner_xlsx(tid):
    if (r := require_login()):
        return r
    row = store.get_trip(g.user["id"], tid)
    if not row:
        abort(404)
    full = hydrate(g.user["id"], row["data"])
    from openpyxl import Workbook
    wb = Workbook()
    wb.remove(wb.active)
    plan.sheet_itinerary(wb, full)
    plan.sheet_packing(wb, full)
    plan.sheet_prep(wb, full)
    plan.sheet_menu(wb, full)
    plan.sheet_shopping(wb, full)
    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    safe = "".join(c for c in row["name"] if c.isalnum() or c in " -_").strip()
    return send_file(
        buf, as_attachment=True,
        download_name=f"{safe or 'planner'}.xlsx",
        mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")


@app.route("/trips/<int:tid>/trip.json")
def trip_json(tid):
    """Export in plan.py's own format, so the CLI can take over."""
    if (r := require_login()):
        return r
    row = store.get_trip(g.user["id"], tid)
    if not row:
        abort(404)
    payload = json.dumps(hydrate(g.user["id"], row["data"]), indent=1)
    return send_file(io.BytesIO(payload.encode()), as_attachment=True,
                     download_name="trip.json", mimetype="application/json")


@app.route("/healthz")
def healthz():
    return {"ok": True}


store.init()

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=int(os.environ.get("PORT", 8000)), debug=True)
